#!/bin/sh
#
# This script is part of Photon, The High Performance PHP Framework.
# Photon, copyrights 2011, Loïc d'Anterroches and contributors.
#
# This script is wrapping photon.php to be able to use:
# - the PHP version of your choice;
# - the Photon version of your choice.
#
# To not use the default set:
# - $PHP_PEAR_PHP_BIN to your PHP binary;
# - $PHP_PHOTON to your photon.php.
#

# first find which PHP binary to use
if test "x$PHP_PEAR_PHP_BIN" != "x"; then
  PHP="$PHP_PEAR_PHP_BIN"
else
  PHP=`pear config-get php_bin`
fi

# Then look at the photon.php
if test "x$PHP_PHOTON" != "x"; then
  PHOTON="$PHP_PHOTON"
else
  # Look for photon.php in the PEAR install dir
  if test "x$PHP_PEAR_INSTALL_DIR" != "x"; then
    INCDIR=$PHP_PEAR_INSTALL_DIR
  else
    INCDIR=`pear config-get php_dir`
  fi
  PHOTON="$INCDIR/photon.php"
fi
# Now, we test if $PHOTON is correctly available, if
# not, hnu may have been called directly from the source
# tree, so we try to find photon.php
if [ ! -f $PHOTON ]; then
    HNU=`readlink -f $0 2>/dev/null`
    if [[ $? == 0 ]]; then
        HNUDIR=`dirname $HNU`
        PHOTON="$HNUDIR/../src/photon.php"
    else
        HNUDIR=`dirname $0`
        PHOTON="$HNUDIR/../src/photon.php"
    fi
    if test "x$PHOTON" = "x"; then
        echo "[ERROR] Unable to find photon.php. Check your installation."
        exit 1
    fi
    echo "[INFO] Running with photon.php from the source installation."
fi

exec $PHP $PHOTON "$@"
