#!/usr/bin/env bash
#
# This script is part of Photon, The High Performance PHP Framework.
# Photon, copyrights 2018, William MARTIN and contributors.
#

# Run the photon version installed in composer with the default PHP interpreter
DIR="$(dirname "$(readlink -f "$0")")"
php $DIR/../src/photon.php "$@"

